# -*- coding: utf-8 -*-
"""finaldraft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167DzC53r6Ieqe7YTIpIpPDDjVnTFGNXP

# Final Project Draft

04/27/26 Monday Commit
"""

'''
Filename: finaldraft.ipynb
Written by: Cricket Bergner
Date: 04/27/26
'''

# import libraries
import numpy as np
from matplotlib import pyplot as plt
from scipy.integrate import solve_ivp as intg    # for integrate

# functions



# main body (3 magnets)

# place three magnets on the ends of an equilateral triangle
magnets3 = [np.array([1, 0]),
          np.array([-0.5, np.sqrt(3)/2]),
          np.array([-0.5, -np.sqrt(3)/2])
]



# extension one (4 magnets)

# place four magnets on the ends of a square
magnets4 = [np.array([1, 0]),
            np.array([1, 1]),
            np.array([0, 1]),
            np.array([0, 0])
]



# extension two (5 magnets)



#################################################################
# END FINAL PROJECT
#################################################################

"""source: https://chalkdustmagazine.com/features/the-magnetic-pendulum/"""